import { SchemeDetail } from "@niti-ai/types";

export const SCHEMES_DATABASE: SchemeDetail[] = [
  {
    id: "scheme-pmegp",
    schemeName: "Prime Minister's Employment Generation Programme",
    shortName: "PMEGP",
    slug: "pmegp",
    summary: "Credit-linked subsidy programme to generate self-employment opportunities through micro-enterprises in manufacturing and service sectors.",
    description: "PMEGP is a flagship credit-linked subsidy scheme administered by the Ministry of MSME through KVIC. The scheme provides financial assistance to establish micro-enterprises, with up to 35% margin money subsidy for rural and special category entrepreneurs (women, SC/ST, OBC, minorities, ex-servicemen, differently-abled).",
    governmentLevel: "central",
    ministry: "Ministry of Micro, Small and Medium Enterprises",
    department: "Khadi and Village Industries Commission (KVIC)",
    implementingAgency: "KVIC, KVIB, and District Industries Centres (DIC)",
    schemeStatus: "active",
    fundingRange: { min: 50000, max: 5000000 },
    subsidyPercentage: 35,
    portalSource: "JanSamarth & KVIC e-Portal",
    sector: "Manufacturing & Services",
    tags: ["High Subsidy", "Rural Priority", "Self-Employment", "JanSamarth"],
    isRealtimeVerified: true,
    liveStatusText: "Open for FY 2026-27 Applications",
    benefitsSummary: [
      "Up to 35% margin money subsidy in rural areas for special category beneficiaries (SC/ST/Women/Minority/OBC).",
      "Up to 25% subsidy for general category beneficiaries in rural areas (15% in urban).",
      "Maximum project cost up to ₹50 Lakh for manufacturing units and ₹20 Lakh for service units.",
      "Bank finance covers 90-95% of project cost with repayment tenure of 3 to 7 years."
    ],
    eligibilityCriteria: {
      minAge: 18,
      maxAge: 70,
      genderAllowed: ["all"],
      socialCategoriesAllowed: ["all"],
      allowedBusinessStages: ["idea", "starting"],
      allowedEnterpriseTypes: ["micro"],
      maxTurnover: 10000000,
      maxFundingSupported: 5000000,
      statesApplicable: ["all"],
      areaTypeAllowed: ["all"]
    },
    documentsRequired: [
      "Aadhaar Card and PAN Card",
      "Detailed Project Report (DPR) with machinery quotes",
      "Educational qualification certificate (minimum 8th pass for manufacturing > ₹10L)",
      "Caste / Category Certificate (if claiming special subsidy)",
      "Rural area certificate issued by Gram Panchayat / local authority",
      "Bank Account details & Passbook copy"
    ],
    applicationProcess: [
      "Register online at the official PMEGP e-Portal or JanSamarth portal.",
      "Fill personal, enterprise, and financing details in the online application form.",
      "Upload required project report, identity proof, and category certificates.",
      "Submit application to chosen District Industries Centre (DIC) or KVIC/KVIB agency.",
      "District Task Force committee reviews and forwards eligible proposals to financing banks for sanction."
    ],
    applicationUrl: "https://www.kviconline.gov.in/pmegpeportal/pmegphome/index.jsp",
    officialSourceUrl: "https://msme.gov.in/schemes/pmegp",
    launchDate: "2008-08-15",
    version: 5,
    lastVerifiedAt: "2026-09-24"
  },
  {
    id: "scheme-standup-india",
    schemeName: "Stand-Up India Scheme for Women and SC/ST Entrepreneurs",
    shortName: "Stand-Up India",
    slug: "standup-india",
    summary: "Bank loans between ₹10 Lakhs and ₹1 Crore to at least one SC/ST and one woman borrower per bank branch for greenfield enterprises.",
    description: "Launched by the Department of Financial Services (DFS), Stand-Up India facilitates bank loans between ₹10 Lakh and ₹100 Lakh to promote entrepreneurship among women and SC/ST communities. The loan covers up to 85% of project cost for setting up new greenfield enterprises across manufacturing, services, agri-allied, or trading sectors.",
    governmentLevel: "central",
    ministry: "Ministry of Finance",
    department: "Department of Financial Services (DFS)",
    implementingAgency: "Scheduled Commercial Banks & SIDBI",
    schemeStatus: "active",
    fundingRange: { min: 1000000, max: 10000000 },
    portalSource: "StandUpMitra & JanSamarth",
    sector: "Greenfield Enterprise (Any Sector)",
    tags: ["Women Entrepreneur", "SC/ST Special", "High Capital", "Collateral-Free Option"],
    isRealtimeVerified: true,
    liveStatusText: "Active in 1.4 Lakh+ Bank Branches",
    benefitsSummary: [
      "Composite loan (term loan + working capital) between ₹10 Lakh and ₹1 Crore.",
      "Margin money requirement reduced to minimum 15% with convergence from state schemes.",
      "Repayment period up to 7 years with a moratorium period of up to 18 months.",
      "Credit guarantee available through Credit Guarantee Fund for Stand Up India (CGFSI)."
    ],
    eligibilityCriteria: {
      minAge: 18,
      genderAllowed: ["female", "male", "transgender"],
      socialCategoriesAllowed: ["sc", "st", "general", "obc"],
      allowedBusinessStages: ["starting"],
      allowedEnterpriseTypes: ["micro", "small"],
      maxFundingSupported: 10000000,
      statesApplicable: ["all"],
      areaTypeAllowed: ["all"]
    },
    documentsRequired: [
      "Identity Proof (Aadhaar / Voter ID / Passport)",
      "Proof of SC/ST category (if applicable) or Women-owned shareholding proof (>=51%)",
      "Business address proof and lease agreement",
      "Detailed project report with projected balance sheet and cash flows",
      "Partnership deed or Memorandum & Articles of Association",
      "Udyam registration and PAN card of the entity"
    ],
    applicationProcess: [
      "Visit StandUpMitra portal (standupmitra.in) or JanSamarth portal.",
      "Register as a borrower and complete the eligibility self-assessment.",
      "Select loan requirements and apply directly to your preferred bank branch.",
      "Track application status online; bank lead officer conducts field appraisal and sanctions loan."
    ],
    applicationUrl: "https://www.standupmitra.in",
    officialSourceUrl: "https://www.standupmitra.in",
    launchDate: "2016-04-05",
    version: 4,
    lastVerifiedAt: "2026-09-24"
  },
  {
    id: "scheme-pm-mudra",
    schemeName: "Pradhan Mantri MUDRA Yojana",
    shortName: "PMMY / Mudra",
    slug: "pm-mudra",
    summary: "Collateral-free institutional micro-credit up to ₹10 Lakhs (and up to ₹20 Lakhs for Tarun Plus) for non-corporate small businesses.",
    description: "MUDRA provides collateral-free loans to non-farm micro and small enterprises. Divided into three tiers: Shishu (loans up to ₹50,000), Kishore (loans ₹50,000 to ₹5 Lakhs), and Tarun (loans ₹5 Lakhs to ₹10 Lakhs, enhanced to ₹20 Lakhs for established enterprises under Union Budget reforms).",
    governmentLevel: "central",
    ministry: "Ministry of Finance",
    department: "Department of Financial Services",
    implementingAgency: "Public & Private Banks, RRBs, MFIs, and NBFCs",
    schemeStatus: "active",
    fundingRange: { min: 10000, max: 2000000 },
    portalSource: "JanSamarth & UdyamiMitra",
    sector: "Micro Business & Trading",
    tags: ["Zero Collateral", "Quick Sanction", "Working Capital", "JanSamarth"],
    isRealtimeVerified: true,
    liveStatusText: "48 Crore+ Loans Sanctioned Nationwide",
    benefitsSummary: [
      "100% collateral-free loan backed by National Credit Guarantee Trustee Company (NCGTC).",
      "Low processing fees and competitive interest rates linked to RBI repo rate.",
      "Three flexible tiers based on business growth stage: Shishu, Kishore, and Tarun.",
      "MUDRA debit card issued for hassle-free working capital withdrawals."
    ],
    eligibilityCriteria: {
      minAge: 18,
      maxAge: 65,
      genderAllowed: ["all"],
      socialCategoriesAllowed: ["all"],
      allowedBusinessStages: ["idea", "starting", "existing", "expansion"],
      allowedEnterpriseTypes: ["micro", "small"],
      maxFundingSupported: 2000000,
      statesApplicable: ["all"],
      areaTypeAllowed: ["all"]
    },
    documentsRequired: [
      "Self-attested Aadhaar and PAN Card",
      "Business address and proof of establishment (Shop Act / Udyam / Trade License)",
      "Bank account statements for the last 6 months",
      "Quotation of machinery/items to be purchased (for term loans)",
      "Passport size photographs"
    ],
    applicationProcess: [
      "Apply through the unified JanSamarth portal (jansamarth.in) under Livelihood Loans.",
      "Digital in-principle sanction is generated within minutes based on credit assessment.",
      "Selected bank branch reviews documentation and disburses funds directly to vendor/borrower."
    ],
    applicationUrl: "https://www.jansamarth.in",
    officialSourceUrl: "https://www.mudra.org.in",
    launchDate: "2015-04-08",
    version: 4,
    lastVerifiedAt: "2026-09-24"
  },
  {
    id: "scheme-cgtmse",
    schemeName: "Credit Guarantee Fund Trust for Micro and Small Enterprises",
    shortName: "CGTMSE",
    slug: "cgtmse",
    summary: "Collateral-free credit facility up to ₹5 Crore for new and existing Micro and Small Enterprises through credit guarantee cover.",
    description: "Jointly set up by the Ministry of MSME and SIDBI, CGTMSE provides credit guarantee coverage up to 85% for micro-enterprises and women/SC/ST entrepreneurs (up to 75-80% for general enterprises) for loans up to ₹5 Crore, enabling businesses to get substantial loans without pledging property or third-party guarantees.",
    governmentLevel: "central",
    ministry: "Ministry of Micro, Small and Medium Enterprises",
    department: "SIDBI & MSME",
    implementingAgency: "Member Lending Institutions (MLIs) / Commercial Banks / NBFCs",
    schemeStatus: "active",
    fundingRange: { min: 500000, max: 50000000 },
    portalSource: "CGTMSE Official & SIDBI",
    sector: "Manufacturing, Services & Retail Trade",
    tags: ["Up to ₹5 Cr", "No Collateral", "SIDBI", "Credit Guarantee"],
    isRealtimeVerified: true,
    liveStatusText: "Guarantee Cap Enhanced to ₹500 Lakhs",
    benefitsSummary: [
      "Credit guarantee cover up to ₹500 Lakhs without requiring third-party collateral.",
      "Guarantee coverage up to 85% for women-owned enterprises and units in North-Eastern states.",
      "Reduced annual guarantee fee structure for micro-enterprises and ZED-certified units.",
      "Covers both fund-based and non-fund-based credit facilities (Bank Guarantees, Letters of Credit)."
    ],
    eligibilityCriteria: {
      minAge: 18,
      genderAllowed: ["all"],
      socialCategoriesAllowed: ["all"],
      allowedBusinessStages: ["starting", "existing", "expansion"],
      allowedEnterpriseTypes: ["micro", "small"],
      maxFundingSupported: 50000000,
      statesApplicable: ["all"],
      areaTypeAllowed: ["all"]
    },
    documentsRequired: [
      "Udyam Registration Certificate",
      "Detailed Project Report (DPR) with financial viability analysis",
      "Audited financial statements for existing units (last 2-3 years)",
      "ITR and GST returns for preceding quarters",
      "KYC documents of promoters and directors"
    ],
    applicationProcess: [
      "Approach any Member Lending Institution (Scheduled Commercial Bank or eligible NBFC).",
      "Submit loan proposal with project report requesting CGTMSE cover.",
      "Bank conducts risk appraisal and sanctions loan without asking for collateral security.",
      "Bank applies for guarantee cover directly to CGTMSE portal on borrower's behalf."
    ],
    applicationUrl: "https://www.cgtmse.in",
    officialSourceUrl: "https://www.cgtmse.in",
    launchDate: "2000-08-01",
    version: 5,
    lastVerifiedAt: "2026-09-24"
  },
  {
    id: "scheme-pm-vishwakarma",
    schemeName: "PM Vishwakarma Scheme for Traditional Artisans & Craftspeople",
    shortName: "PM Vishwakarma",
    slug: "pm-vishwakarma",
    summary: "End-to-end holistic support, ₹15,000 tool kit incentive, skill training with stipend, and collateral-free enterprise credit up to ₹3 Lakh at 5% interest.",
    description: "A Central Sector Scheme launched to provide holistic institutional support to traditional artisans and craftspeople working with hands and tools across 18 recognized traditional trades (carpenters, blacksmiths, potters, sculptors, cobblers, tailors, etc.). Provides modern training, digital incentives, marketing support, and subsidized loans.",
    governmentLevel: "central",
    ministry: "Ministry of Micro, Small and Medium Enterprises",
    department: "Ministry of Skill Development & Entrepreneurship",
    implementingAgency: "MSME-DFO, National Skill Development Corporation (NSDC), and Banks",
    schemeStatus: "active",
    fundingRange: { min: 15000, max: 300000 },
    subsidyPercentage: 8, // Interest subvention of 8%
    portalSource: "PM Vishwakarma Portal",
    sector: "Artisans & Handicrafts (18 Traditional Trades)",
    tags: ["Artisans", "Toolkit Grant ₹15k", "5% Concessional Interest", "PM Portal"],
    isRealtimeVerified: true,
    liveStatusText: "Enrollment Open at All CSCs Nationwide",
    benefitsSummary: [
      "PM Vishwakarma Certificate and ID Card recognizing professional artisan status.",
      "Basic skill training of 5-7 days with ₹500/day stipend, followed by advanced 15-day training.",
      "Toolkit incentive of ₹15,000 e-voucher for purchasing modern precision equipment.",
      "Collateral-free enterprise credit: ₹1 Lakh (Tranche 1 for 18 months) and ₹2 Lakhs (Tranche 2 for 30 months) at highly subsidized 5% interest rate with 8% subvention borne by GoI."
    ],
    eligibilityCriteria: {
      minAge: 18,
      genderAllowed: ["all"],
      socialCategoriesAllowed: ["all"],
      allowedBusinessStages: ["idea", "starting", "existing"],
      allowedEnterpriseTypes: ["micro"],
      maxFundingSupported: 300000,
      statesApplicable: ["all"],
      areaTypeAllowed: ["all"]
    },
    documentsRequired: [
      "Aadhaar Card (linked to active mobile number)",
      "Bank Passbook / Account details",
      "Ration Card or Family details",
      "Trade declaration verifying engagement in one of the 18 specified trades"
    ],
    applicationProcess: [
      "Visit any Common Service Centre (CSC) or apply online at pmvishwakarma.gov.in.",
      "Three-step verification: Gram Panchayat / Urban Local Body verification, followed by District Implementation Committee, and National Committee approval.",
      "Receive digital Vishwakarma ID, attend skill training, claim ₹15k toolkit voucher, and access concessional bank loan."
    ],
    applicationUrl: "https://pmvishwakarma.gov.in",
    officialSourceUrl: "https://pmvishwakarma.gov.in",
    launchDate: "2023-09-17",
    version: 3,
    lastVerifiedAt: "2026-09-24"
  },
  {
    id: "scheme-sisfs",
    schemeName: "Startup India Seed Fund Scheme",
    shortName: "SISFS",
    slug: "sisfs",
    summary: "Financial assistance up to ₹50 Lakhs to DPIIT-recognized startups for proof of concept, prototype development, product trials, and commercialization.",
    description: "Administered by the Department for Promotion of Industry and Internal Trade (DPIIT), SISFS provides financial support to innovative startups through selected incubators across India. Offers up to ₹20 Lakhs as grant for proof of concept/prototype, and up to ₹50 Lakhs as debt/convertible debentures for commercialization.",
    governmentLevel: "central",
    ministry: "Ministry of Commerce and Industry",
    department: "DPIIT (Department for Promotion of Industry and Internal Trade)",
    implementingAgency: "Startup India & Selected Approved Incubators",
    schemeStatus: "active",
    fundingRange: { min: 500000, max: 5000000 },
    portalSource: "Startup India Portal",
    sector: "Technology & Innovative Startups",
    tags: ["Startup Grant", "DPIIT", "Equity-Free Option", "Incubators"],
    isRealtimeVerified: true,
    liveStatusText: "Applications Active on Startup India Portal",
    benefitsSummary: [
      "Up to ₹20 Lakhs grant for validation of proof of concept, prototype development, and product trials.",
      "Up to ₹50 Lakhs investment through convertible debentures or debt-linked instruments for commercial market rollout.",
      "Access to incubator mentoring, lab infrastructure, legal support, and investor network."
    ],
    eligibilityCriteria: {
      minAge: 18,
      genderAllowed: ["all"],
      socialCategoriesAllowed: ["all"],
      allowedBusinessStages: ["idea", "starting"],
      allowedEnterpriseTypes: ["micro", "small"],
      maxTurnover: 25000000,
      maxFundingSupported: 5000000,
      statesApplicable: ["all"],
      areaTypeAllowed: ["all"]
    },
    documentsRequired: [
      "DPIIT Startup Recognition Certificate",
      "Pitch Deck detailing innovative concept, market need, and business model",
      "Company Incorporation Certificate (incorporated not more than 2 years ago)",
      "Brief on proposed use of funds and milestone timeline"
    ],
    applicationProcess: [
      "Register and obtain DPIIT recognition on startupindia.gov.in.",
      "Apply online for SISFS, choosing up to 3 approved incubators in order of preference.",
      "Incubator Seed Management Committee evaluates presentation and awards milestone-based funds."
    ],
    applicationUrl: "https://seedfund.startupindia.gov.in",
    officialSourceUrl: "https://www.startupindia.gov.in",
    launchDate: "2021-04-01",
    version: 4,
    lastVerifiedAt: "2026-09-24"
  },
  {
    id: "scheme-pmfme",
    schemeName: "PM Formalisation of Micro Food Processing Enterprises Scheme",
    shortName: "PMFME",
    slug: "pmfme",
    summary: "35% credit-linked capital subsidy up to ₹10 Lakhs for micro food processing units under the One District One Product (ODOP) framework.",
    description: "Under the Ministry of Food Processing Industries (MoFPI), PMFME aims to formalize and upgrade micro food processing units. Individual micro-enterprises receive 35% credit-linked capital subsidy with a maximum ceiling of ₹10 Lakh per unit, alongside branding and marketing support.",
    governmentLevel: "central",
    ministry: "Ministry of Food Processing Industries (MoFPI)",
    department: "National Institute of Food Technology Entrepreneurship and Management (NIFTEM)",
    implementingAgency: "State Nodal Agencies (SNA) and Commercial Banks",
    schemeStatus: "active",
    fundingRange: { min: 100000, max: 3000000 },
    subsidyPercentage: 35,
    portalSource: "MoFPI PMFME Portal",
    sector: "Food Processing & Agri-Value Addition",
    tags: ["35% Subsidy", "ODOP", "Agri-Food", "MoFPI"],
    isRealtimeVerified: true,
    liveStatusText: "ODOP Applications Open Across 713 Districts",
    benefitsSummary: [
      "35% credit-linked capital subsidy on eligible project cost up to a maximum of ₹10 Lakhs.",
      "Beneficiary contribution minimum 10% of project cost, remaining funded by commercial bank loan.",
      "Seed capital of ₹40,000 per SHG member for working capital and minor tools.",
      "Free technical training, FSSAI registration assistance, and packaging/branding support."
    ],
    eligibilityCriteria: {
      minAge: 18,
      genderAllowed: ["all"],
      socialCategoriesAllowed: ["all"],
      allowedBusinessStages: ["starting", "existing", "expansion"],
      allowedEnterpriseTypes: ["micro"],
      maxFundingSupported: 3000000,
      statesApplicable: ["all"],
      areaTypeAllowed: ["all"]
    },
    documentsRequired: [
      "Aadhaar, PAN, and address proof",
      "Detailed Project Report (DPR) for food processing machinery and building",
      "Quotation of food grade machinery with GST from certified vendors",
      "Existing FSSAI license or undertaking to acquire one",
      "Bank account statements for last 6 months"
    ],
    applicationProcess: [
      "Register on the PMFME MIS portal (pmfme.mofpi.gov.in).",
      "District Resource Person (DRP) assists in preparing DPR and filing application.",
      "District Level Committee recommends proposal to financing bank for sanction and subsidy release."
    ],
    applicationUrl: "https://pmfme.mofpi.gov.in",
    officialSourceUrl: "https://mofpi.gov.in/pmfme",
    launchDate: "2020-06-29",
    version: 4,
    lastVerifiedAt: "2026-09-24"
  },
  {
    id: "scheme-msme-zed",
    schemeName: "MSME Sustainable (ZED) Certification & Financial Assistance",
    shortName: "ZED Certification",
    slug: "msme-zed",
    summary: "Up to 80% government subsidy on certification cost plus ₹5 Lakhs financial assistance for technology adoption to achieve Zero Defect Zero Effect manufacturing.",
    description: "The ZED scheme by the Ministry of MSME motivates manufacturers to produce zero-defect goods with zero negative environmental impact. Provides financial support up to ₹5 Lakhs for consulting and technology adoption, concession on loan processing fees and interest rates from partner banks, and certification subsidies up to 80%.",
    governmentLevel: "central",
    ministry: "Ministry of Micro, Small and Medium Enterprises",
    department: "Quality Council of India (QCI) & MSME",
    implementingAgency: "QCI & Certified Assessment Agencies",
    schemeStatus: "active",
    fundingRange: { min: 10000, max: 500000 },
    subsidyPercentage: 80,
    portalSource: "MSME Champions & ZED Portal",
    sector: "Manufacturing & Clean Tech",
    tags: ["Green Manufacturing", "ZED Certification", "Bank Concessions", "MSME Champions"],
    isRealtimeVerified: true,
    liveStatusText: "Bronze, Silver & Gold Certification Open",
    benefitsSummary: [
      "80% subsidy for Micro, 60% for Small, and 50% for Medium enterprises on certification fees.",
      "Additional 10% subsidy for women-owned and SC/ST-owned enterprises.",
      "Up to ₹5 Lakhs financial assistance per MSME for technical consulting, handholding, and clean tech adoption.",
      "Lower interest rates (0.25% to 0.50% concession) and waiver of processing fees at partner banks."
    ],
    eligibilityCriteria: {
      minAge: 18,
      genderAllowed: ["all"],
      socialCategoriesAllowed: ["all"],
      allowedBusinessStages: ["existing", "expansion"],
      allowedEnterpriseTypes: ["micro", "small", "medium"],
      maxFundingSupported: 500000,
      statesApplicable: ["all"],
      areaTypeAllowed: ["all"]
    },
    documentsRequired: [
      "Valid Udyam Registration Number",
      "Factory / Production facility address and photos",
      "Quality and safety records / self-assessment declaration"
    ],
    applicationProcess: [
      "Register on zed.msme.gov.in using your Udyam number.",
      "Complete free online self-assessment and choose certification level (Bronze/Silver/Gold).",
      "Desktop evaluation and site audit conducted by accredited agency; get subsidy and certificate directly."
    ],
    applicationUrl: "https://zed.msme.gov.in",
    officialSourceUrl: "https://msme.gov.in/schemes/zed",
    launchDate: "2022-04-28",
    version: 3,
    lastVerifiedAt: "2026-09-24"
  },
  {
    id: "scheme-nssh",
    schemeName: "National SC-ST Hub (NSSH) Financial Assistance",
    shortName: "National SC-ST Hub",
    slug: "nssh",
    summary: "Dedicated financial subsidies, 25% reimbursement on testing & certification fees, and up to ₹1 Lakh reimbursement on bank processing fees for SC/ST MSMEs.",
    description: "Set up by the Ministry of MSME to assist Scheduled Caste and Scheduled Tribe entrepreneurs in participating in public procurement and modern manufacturing. Provides special subsidies for participation in national/international exhibitions, vendor development programs, bank processing fee reimbursements, and technology upgrades.",
    governmentLevel: "central",
    ministry: "Ministry of Micro, Small and Medium Enterprises",
    department: "National Small Industries Corporation (NSIC)",
    implementingAgency: "NSIC & NSSH Field Offices",
    schemeStatus: "active",
    fundingRange: { min: 25000, max: 1000000 },
    subsidyPercentage: 80,
    portalSource: "NSSH Portal & NSIC",
    sector: "SC/ST Enterprises (All Sectors)",
    tags: ["SC/ST Priority", "Procurement Quota 4%", "Fee Reimbursement", "NSIC"],
    isRealtimeVerified: true,
    liveStatusText: "Active with Dedicated NSSH Helplines",
    benefitsSummary: [
      "Assistance to fulfill the mandatory 4% annual public procurement target from SC/ST enterprises by Central Public Sector Enterprises (CPSEs).",
      "100% reimbursement of bank loan processing fees up to ₹1 Lakh.",
      "80% subsidy for participation in domestic and international trade fairs and exhibitions.",
      "Reimbursement of rating fees, testing charges, and BIS/ISO certification costs."
    ],
    eligibilityCriteria: {
      minAge: 18,
      genderAllowed: ["all"],
      socialCategoriesAllowed: ["sc", "st"],
      allowedBusinessStages: ["starting", "existing", "expansion"],
      allowedEnterpriseTypes: ["micro", "small", "medium"],
      maxFundingSupported: 1000000,
      statesApplicable: ["all"],
      areaTypeAllowed: ["all"]
    },
    documentsRequired: [
      "Udyam Registration Certificate with SC/ST category flagged",
      "Caste Certificate of proprietor / majority partners / directors",
      "Bank sanction letter and loan processing fee debit receipt",
      "GST returns and cancelled cheque"
    ],
    applicationProcess: [
      "Register on the National SC-ST Hub portal (scsthub.in).",
      "Submit reimbursement claims online along with supporting fee receipts.",
      "NSIC branch office verifies documents and transfers reimbursement directly via DBT."
    ],
    applicationUrl: "https://www.scsthub.in",
    officialSourceUrl: "https://msme.gov.in/schemes/national-sc-st-hub",
    launchDate: "2016-10-18",
    version: 4,
    lastVerifiedAt: "2026-09-24"
  },
  {
    id: "scheme-mp-msme-2021",
    schemeName: "Madhya Pradesh MSME Development Policy & Financial Incentives",
    shortName: "MP MSME Policy",
    slug: "mp-msme-policy",
    summary: "Up to 40% capital investment subsidy, 5% interest subsidy for 5 years, and power tariff assistance for enterprises in Madhya Pradesh.",
    description: "The Madhya Pradesh MSME Industrial Policy offers strong fiscal incentives to attract industrial investment and generate regional employment. Units in notified backward districts, food processing, renewable energy, and those owned by women or SC/ST founders qualify for the highest subsidy tier.",
    governmentLevel: "state",
    ministry: "Department of Micro, Small and Medium Enterprises, Govt. of MP",
    department: "Directorate of Industries, Madhya Pradesh",
    implementingAgency: "District Industries and Trade Centres (DITC), MP",
    schemeStatus: "active",
    fundingRange: { min: 100000, max: 20000000 },
    subsidyPercentage: 40,
    portalSource: "MP MSME Portal (msme.mponline.gov.in)",
    sector: "Manufacturing & Industrial Production",
    tags: ["State Policy", "40% Capital Subsidy", "Madhya Pradesh", "Interest Subsidy"],
    isRealtimeVerified: true,
    liveStatusText: "Active under MP MSME Policy 2021 (Amended)",
    benefitsSummary: [
      "Capital investment subsidy up to 40% on plant, machinery, and industrial building cost.",
      "Additional 2% to 5% special subsidy for women, SC/ST, and Divyang entrepreneurs.",
      "5% interest subsidy on bank term loans for a period of 5 years (maximum ₹20 Lakhs per annum).",
      "Electricity duty exemption and ₹1 per unit power tariff concession for 5 years."
    ],
    eligibilityCriteria: {
      minAge: 18,
      genderAllowed: ["all"],
      socialCategoriesAllowed: ["all"],
      allowedBusinessStages: ["starting", "expansion"],
      allowedEnterpriseTypes: ["micro", "small", "medium"],
      maxFundingSupported: 20000000,
      statesApplicable: ["Madhya Pradesh"],
      areaTypeAllowed: ["all"]
    },
    documentsRequired: [
      "Udyam Registration Certificate in Madhya Pradesh",
      "Factory Land lease deed or Industrial Area allotment order (AKVN / DIC)",
      "Bank Loan Sanction letter and disbursement certificate",
      "CA Certified Capital Investment Certificate and machinery invoices",
      "Consent to Establish / Operate from MP Pollution Control Board (MPPCB)"
    ],
    applicationProcess: [
      "Log into MP MSME portal (msme.mponline.gov.in) with Udyam and SSO ID.",
      "Select policy incentive module and submit financial/investment details.",
      "Physical verification conducted by General Manager, DITC; State Level Committee sanctions subsidy."
    ],
    applicationUrl: "https://msme.mponline.gov.in",
    officialSourceUrl: "https://industries.mp.gov.in",
    launchDate: "2021-04-01",
    version: 3,
    lastVerifiedAt: "2026-09-24"
  },
  {
    id: "scheme-maha-cmegp",
    schemeName: "Maharashtra Chief Minister Employment Generation Programme",
    shortName: "Maha CMEGP",
    slug: "maha-cmegp",
    summary: "Credit-linked subsidy up to 35% with project cost up to ₹50 Lakhs for manufacturing and ₹20 Lakhs for services in Maharashtra.",
    description: "CMEGP is the Maharashtra State Government's flagship self-employment program. Aimed at generating 1 Lakh micro-enterprises over 5 years, it provides 15% to 35% margin money subsidy across both rural and urban areas with accelerated sanctioning via nationalized and private banks.",
    governmentLevel: "state",
    ministry: "Industries Department, Government of Maharashtra",
    department: "Directorate of Industries, Maharashtra",
    implementingAgency: "District Industries Centre (DIC) & Maharashtra State KVIB",
    schemeStatus: "active",
    fundingRange: { min: 100000, max: 5000000 },
    subsidyPercentage: 35,
    portalSource: "Maharashtra CMEGP Portal",
    sector: "Manufacturing, Agro-Processing & Services",
    tags: ["State Policy", "Maharashtra", "35% Margin Money", "CMEGP"],
    isRealtimeVerified: true,
    liveStatusText: "Online Portal Accepting 2026-27 Batches",
    benefitsSummary: [
      "Up to 35% subsidy for special category (SC/ST/Women/Ex-servicemen/OBC) in rural Maharashtra.",
      "Up to 25% subsidy for general category in rural areas and 15% in urban areas.",
      "Maximum project cost up to ₹50 Lakh for manufacturing units and ₹20 Lakh for services.",
      "Tie-ups with SBI, Bank of Maharashtra, Bank of Baroda for simplified loan disbursement."
    ],
    eligibilityCriteria: {
      minAge: 18,
      maxAge: 45,
      genderAllowed: ["all"],
      socialCategoriesAllowed: ["all"],
      allowedBusinessStages: ["idea", "starting"],
      allowedEnterpriseTypes: ["micro"],
      maxFundingSupported: 5000000,
      statesApplicable: ["Maharashtra"],
      areaTypeAllowed: ["all"]
    },
    documentsRequired: [
      "Domicile Certificate of Maharashtra",
      "Aadhaar and PAN Card",
      "Detailed Project Report (DPR)",
      "Educational qualification certificate (minimum 10th pass for projects > ₹10L)",
      "Caste / Category Certificate (if applicable)"
    ],
    applicationProcess: [
      "Apply online on mahacmegp.gov.in.",
      "Online scrutiny by General Manager DIC within 14 working days.",
      "Interview by District Task Force Committee; sanctioned loan disbursed by partner bank."
    ],
    applicationUrl: "https://maha-cmegp.gov.in",
    officialSourceUrl: "https://maha-cmegp.gov.in",
    launchDate: "2019-08-01",
    version: 4,
    lastVerifiedAt: "2026-09-24"
  },
  {
    id: "scheme-up-odop",
    schemeName: "Uttar Pradesh One District One Product (ODOP) Margin Money Scheme",
    shortName: "UP ODOP Scheme",
    slug: "up-odop-scheme",
    summary: "25% margin money subsidy up to ₹20 Lakhs to revitalize traditional crafts, food products, and indigenous industries in Uttar Pradesh.",
    description: "The UP ODOP initiative preserves and promotes traditional product clusters across 75 districts of Uttar Pradesh (e.g. Leather in Agra/Kanpur, Chikankari in Lucknow, Brassware in Moradabad, Carpets in Bhadohi). Provides up to 25% margin money subsidy to establish or modernize manufacturing units.",
    governmentLevel: "state",
    ministry: "Department of MSME and Export Promotion, Govt. of UP",
    department: "Directorate of Industries, Uttar Pradesh",
    implementingAgency: "District Industries & Enterprise Promotion Centre (DIEPC), UP",
    schemeStatus: "active",
    fundingRange: { min: 50000, max: 2500000 },
    subsidyPercentage: 25,
    portalSource: "UP DIUP / ODOP Portal",
    sector: "Artisanal Crafts, Textiles & District Specialties",
    tags: ["State Policy", "Uttar Pradesh", "ODOP", "Handicrafts Subsidy"],
    isRealtimeVerified: true,
    liveStatusText: "75 District Clusters Actively Funded",
    benefitsSummary: [
      "Subsidy of 25% of total project cost (max ₹6.25 Lakhs) for projects up to ₹25 Lakhs.",
      "Subsidy of 20% (max ₹10 Lakhs) for projects between ₹25 Lakhs and ₹50 Lakhs.",
      "Subsidy of 10% (max ₹20 Lakhs) for projects between ₹50 Lakhs and ₹250 Lakhs.",
      "Free design workshops, global marketing pavilions, and Amazon/Flipkart onboarding assistance."
    ],
    eligibilityCriteria: {
      minAge: 18,
      genderAllowed: ["all"],
      socialCategoriesAllowed: ["all"],
      allowedBusinessStages: ["idea", "starting", "existing", "expansion"],
      allowedEnterpriseTypes: ["micro", "small"],
      maxFundingSupported: 25000000,
      statesApplicable: ["Uttar Pradesh"],
      areaTypeAllowed: ["all"]
    },
    documentsRequired: [
      "Domicile Certificate of Uttar Pradesh",
      "Aadhaar and PAN Card",
      "Project Report aligned with the specific ODOP product of the district",
      "Educational certificate and bank quotation"
    ],
    applicationProcess: [
      "Apply online at diupmsme.upsdc.gov.in.",
      "District Level Task Force verifies that the project matches the notification of that district's ODOP product.",
      "Approved files sent to financing bank; margin money released upon physical unit verification."
    ],
    applicationUrl: "https://diupmsme.upsdc.gov.in",
    officialSourceUrl: "https://odopup.in",
    launchDate: "2018-01-24",
    version: 4,
    lastVerifiedAt: "2026-09-24"
  },
  {
    id: "scheme-tn-needs",
    schemeName: "Tamil Nadu New Entrepreneur-cum-Enterprise Development Scheme",
    shortName: "Tamil Nadu NEEDS",
    slug: "tamil-nadu-needs",
    summary: "25% capital subsidy up to ₹75 Lakhs with 3% interest rebate for first-generation educated entrepreneurs in Tamil Nadu.",
    description: "NEEDS is an initiative of the Government of Tamil Nadu to assist first-generation educated youth in establishing manufacturing or service enterprises. Offers a substantial 25% capital subsidy (capped at ₹75 Lakhs) coupled with entrepreneurship development training by EDI.",
    governmentLevel: "state",
    ministry: "Micro, Small and Medium Enterprises Department, Govt. of Tamil Nadu",
    department: "Directorate of Industries and Commerce, Chennai",
    implementingAgency: "District Industries Centre (DIC) and TIIC",
    schemeStatus: "active",
    fundingRange: { min: 1000000, max: 50000000 },
    subsidyPercentage: 25,
    portalSource: "MSME Tamil Nadu Single Window Portal",
    sector: "Manufacturing & Knowledge Services",
    tags: ["State Policy", "Tamil Nadu", "Up to ₹75L Subsidy", "First-Gen Founder"],
    isRealtimeVerified: true,
    liveStatusText: "Target: 1,000+ Entrepreneurs per Annum",
    benefitsSummary: [
      "25% State Capital Subsidy on project cost with a ceiling of ₹75 Lakhs.",
      "3% interest subvention for the entire repayment tenure of the bank loan.",
      "Mandatory residential EDP training through Entrepreneurship Development and Innovation Institute (EDII).",
      "Financing options through Tamil Nadu Industrial Investment Corporation (TIIC) or commercial banks."
    ],
    eligibilityCriteria: {
      minAge: 21,
      maxAge: 45,
      genderAllowed: ["all"],
      socialCategoriesAllowed: ["all"],
      allowedBusinessStages: ["idea", "starting"],
      allowedEnterpriseTypes: ["micro", "small"],
      maxFundingSupported: 50000000,
      statesApplicable: ["Tamil Nadu"],
      areaTypeAllowed: ["all"]
    },
    documentsRequired: [
      "Degree / Diploma / ITI educational certificates",
      "Nativity / Community Certificate of Tamil Nadu",
      "Detailed Project Report with land and machinery estimation",
      "Partnership deed or company incorporation (first generation promoter declaration)"
    ],
    applicationProcess: [
      "Apply online on msmeonline.tn.gov.in.",
      "Task Force Committee headed by District Collector interviews and selects candidates.",
      "Undergo EDII training, after which bank disburses term loan and subsidy is adjusted."
    ],
    applicationUrl: "https://www.msmeonline.tn.gov.in/needs",
    officialSourceUrl: "https://www.msmeonline.tn.gov.in",
    launchDate: "2012-08-15",
    version: 4,
    lastVerifiedAt: "2026-09-24"
  },
  {
    id: "scheme-karnataka-elevate",
    schemeName: "Karnataka ELEVATE 100 & Idea2PoC Innovation Grant",
    shortName: "Karnataka ELEVATE",
    slug: "karnataka-elevate",
    summary: "Up to ₹50 Lakhs equity-free grant-in-aid to tech startups, rural innovators, and women-led ventures in Karnataka.",
    description: "Organized by the Department of Electronics, IT, BT and S&T, Government of Karnataka, ELEVATE identifies and nurtures top innovative startups in Karnataka by providing non-dilutive grant-in-aid up to ₹50 Lakhs along with incubation, subsidized cloud credits, and government mentorship.",
    governmentLevel: "state",
    ministry: "Department of Electronics, IT, BT and S&T, Govt. of Karnataka",
    department: "Mission for Incubation and Startup Karnataka",
    implementingAgency: "K-Tech & Karnataka Innovation and Technology Society (KITS)",
    schemeStatus: "active",
    fundingRange: { min: 1000000, max: 5000000 },
    portalSource: "Startup Karnataka Portal",
    sector: "DeepTech, AgriTech, MedTech, AI & CleanTech",
    tags: ["State Policy", "Karnataka", "Equity-Free ₹50L", "Tech Startups"],
    isRealtimeVerified: true,
    liveStatusText: "Call for Applications Open for Current Cohort",
    benefitsSummary: [
      "Up to ₹50 Lakhs grant-in-aid disbursed in milestone tranches without taking equity.",
      "Subsidized access to K-Tech Centers of Excellence, prototyping labs, and supercomputers.",
      "Free patent filing support and intellectual property reimbursement up to ₹2 Lakhs.",
      "Priority consideration for government procurement under Karnataka Startup Policy."
    ],
    eligibilityCriteria: {
      minAge: 18,
      genderAllowed: ["all"],
      socialCategoriesAllowed: ["all"],
      allowedBusinessStages: ["idea", "starting"],
      allowedEnterpriseTypes: ["micro", "small"],
      maxTurnover: 25000000,
      maxFundingSupported: 5000000,
      statesApplicable: ["Karnataka"],
      areaTypeAllowed: ["all"]
    },
    documentsRequired: [
      "Startup Karnataka Registration Certificate",
      "Company Registration (Pvt Ltd / LLP incorporated in Karnataka)",
      "Technical Pitch Deck and product architecture",
      "Proof that at least 50% of workforce is based in Karnataka"
    ],
    applicationProcess: [
      "Submit application on startup.karnataka.gov.in during the open call window.",
      "Shortlisted startups pitch before sector-specific jury panels of venture capitalists and scientists.",
      "High-level committee announces winners; funding released against agreed milestone deliverables."
    ],
    applicationUrl: "https://startup.karnataka.gov.in",
    officialSourceUrl: "https://startup.karnataka.gov.in",
    launchDate: "2017-07-01",
    version: 4,
    lastVerifiedAt: "2026-09-24"
  }
];
